### PR TITLE
Print the JSON body if the deserialization fails and accept long payloads

### LINKED ISSUE #20: Add the body of the JSON to the error if the deserialization fails
This is also needed due to the fact that actix has a limit on the body size which may be too low for some apps.

### PR DESCRIPTION
**Pull request by marmistrz**
Closes #20. 
Example error output:

```
[2019-03-11T15:29:32Z INFO  gumpi::session] Creating a slot
[2019-03-11T15:29:32Z INFO  gumpi::session] Uploading a file, id = 1
[2019-03-11T15:29:32Z INFO  gumpi::session] Uploaded a file, id = 1
[2019-03-11T15:29:32Z INFO  gumpi::session::mpi] Downloading the hostfile...
[2019-03-11T15:29:32Z INFO  gumpi::session::mpi] Downloaded: Ok("\"http://127.0.0.1:61622/sessions/2/blobs/1\" file downloaded")
[2019-03-11T15:29:32Z INFO  gumpi::session::mpi] Executing mpirun with args ["--mca", "btl_tcp_if_include", "10.30.8.0/22", "-n", "12", "--hostfile", "hostfile", "game-life", "3", "2", "12000", "10"]...
[2019-03-11T15:29:32Z INFO  gumpi::session] Reply: Session closed
error: Command execution: Deserialization failed: invalid type: sequence, expected a string at line 1 column 7
Original string:
{"Err":["failed to execute command: /home/marcin/.local/share/golemunlimited/sessions/hd/82c10b7b-1e11-4cd8-8d0b-33d3340e79bf/mpirun, [\"--mca\", \"btl_tcp_if_include\", \"10.30.8.0/22\", \"-n\", \"12\", \"--hostfile\", \"hostfile\", \"game-life\", \"3\", \"2\", \"12000\", \"10\"], Output { status: ExitStatus(ExitStatus(256)), stdout: \"\", stderr: \"--------------------------------------------------------------------------\\nThere are not enough slots available in the system to satisfy the 12 slots\\nthat were requested by the application:\\n  game-life\\n\\nEither request fewer slots for your application, or make more slots available\\nfor use.\\n--------------------------------------------------------------------------\\n\" }"]}
```

### CODE REVIEW

File: src/session.rs [hunk 1]
```diff
@@ -261,6 +262,34 @@ impl Drop for HubSession {
 
 type BlobId = u64;
 
+#[derive(Debug, Fail)]
+#[fail(
+    display = "Deserialization failed: {}. Original string: {}",
+    error, raw_json
+)]
+pub struct DeserializationError {
+    error: serde_json::Error,
```
Comment (prekucki) [inline src/session.rs]: #[fail(cause)]

File: src/session.rs [hunk 2]
```diff
@@ -261,6 +262,34 @@ impl Drop for HubSession {
...
+    raw_json: DisplayBytes,
+}
+
+#[derive(Debug)]
+pub struct DisplayBytes(Bytes);
```
Comment (prekucki) [inline src/session.rs]: is pub required?
